#include <iostream>

#include <main.hpp>
#include <utility/util.hpp>

// algorithm
extern void test_a01_02_subset_k_len();
extern void test_a01_01_subset_all();
extern void test_a01_03_cont_subarray();
extern void test_a01_04_permutation();

// epi
extern void test_p4_1_parity();
extern void test_p4_2_bit_swap();
extern void test_p4_3_bit_reverse();
extern void test_closed_same_bit_cnt_num();
extern void test_add_mul_with_bit_op();
extern void test_div_with_bit_op();
extern void test_pow_bit_op();
extern void test_num_reverse();
extern void test_palindrom_num();
extern void test_p4_10_random_num_bit_op();
extern void test_p4_11_intersect_rec();
extern void test_p4_tmp_1_4_align();
extern void test_p5_1_dutch_flag_partition();
extern void test_p5_2_add_one();
extern void test_p5_3_mul_bignum();
extern void test_p5_4_array_mv();
extern void test_p5_5_rem_dup();
extern void test_stock_trading();
extern void test_p5_7_stock_trading_twice();
extern void test_p5_8_quicksort_repeat_big_small();
extern void test_p5_9_generate_prime();
extern void test_p5_10_permutation_locating();
extern void test_p5_11_permutation_next();
extern void test_p5_12_sampling_offline();
extern void test_p5_13_sampling_online();
extern void test_p5_14_random_permutation();
extern void test_p5_15_random_subset();
extern void test_p5_16_non_uniform_random();
extern void test_p5_17_validate_sudoku_sol();
extern void test_p5_18_read_spiral_order();
extern void test_p5_19_rotate_right();
extern void test_p5_20_pascal_triangle();
extern void test_p6_1_itos_stoi();
extern void test_p6_2_base_transform();
extern void test_p6_3_spreadsheet_colum_num();
extern void test_p6_4_replace_rm();
extern void test_p6_5_palindrom();
extern void test_p6_6_reverse_word();
extern void test_p6_7_look_and_say();
extern void test_p6_8_roman_to_i();
extern void test_p6_9_gen_valid_ip();
extern void test_p6_10_snake_string();
extern void test_p6_11_string_compress();
extern void test_p6_12_rabin_karp_search();
extern void test_p7_0_linked_list();
extern void test_p7_1_merge_sorted_linkedlist();
extern void test_p7_2_reverse_linked_list();
extern void test_p7_3_cycle_detect();
extern void test_p7_4_overlap_check();
extern void test_p7_5_test_overlap_check_cycle();
extern void test_p7_6_delete_o_1();
extern void test_p7_7_remove_kth_from_last();
extern void test_p7_8_remove_duplicated();
extern void test_p7_9_right_shift();
extern void test_p7_10_even_odd_merge();
extern void test_p7_11_is_palindrome();
extern void test_p7_12_list_partition();
extern void test_p7_13_list_int_add();
extern void test_p8_1_max_value();
extern void test_p8_2_calc_rpn();
extern void test_p8_3_parenthesis();
extern void test_p8_4_normalize_path();
extern void test_p8_5_building_suset();
extern void test_p8_6_tree_level();
extern void test_p8_7_circular_queue();
extern void test_p8_8_que_with_stack();
extern void test_p8_9_que_with_max();
extern void test_p9_1_check_balanced();
extern void test_p9_2_check_symetric();
extern void test_p9_3_lca_no_parent_link();
extern void test_p9_4_lca_with_parent_link();
extern void test_p9_5_path_bit_sum();
extern void test_p9_6_find_same_weigh();
extern void test_p9_7_inorder_traverse_loop();
extern void test_p9_8_k_th_ele_in_inorder_traverse();
extern void test_p9_9_successor_o_1();
extern void test_p9_10_traverse_s_1();
extern void test_p9_11_const_tree();
extern void test_p9_12_const_tree_marker();
extern void test_p9_13_leaf_list();
extern void test_p9_14_exterior_node();
extern void test_p9_15_right_sibling();
extern void test_p10_heap_bootcamp();
extern void test_p10_1_merge_sorted();
extern void test_p10_2_sort_k_inc_dec_array();
extern void test_p10_3_sort_almost_sorted();
extern void test_p10_4_nearest_start();
extern void test_p10_5_realtime_median();
extern void test_p10_6_max_k_in_max_heap();
extern void test_00_binarysearch_bootcamp();
extern void test_p11_1_first_k();
extern void test_p11_2_same_value_with_idx();
extern void test_p11_3_min_in_circular_array();
extern void test_p11_4_max_square_root();
extern void test_p11_5_square_root_real();
extern void test_p11_6_search_sorted_matrix();
extern void test_p11_7_min_max();
extern void test_p11_8_kth_big();
extern void test_p11_9_missing_ip();
extern void test_p11_10_dup_missing_ele();
extern void test_p12_00_hashtable_boot();
extern void test_p12_01_check_palindrom();
extern void test_p12_02_anony_mail_with_magazine();
extern void test_p12_03_isbn_cache();
extern void test_p12_04_lca_with_hash();
extern void test_p12_05_closest_dup_str();
extern void test_p12_06_min_sub_vect();
extern void test_p12_07_min_sub_vect_ordered();
extern void test_p12_08_longest_sub_vec();
extern void test_p12_09_longest_cont_num_seq();
extern void test_p12_10_find_appended_words();
extern void test_p12_11_collatz_conjecture();
extern void test_p13_00_sort_bootcamp();
extern void test_p13_01_intersection_of_sorted_vec();
extern void test_p13_02_merge_sorted();
extern void test_p13_03_h_index();
extern void test_p13_04_rm_dup_name();
extern void test_p13_05_impossible_min_num();
extern void test_p13_06_calendar_max_dup_sch();
extern void test_p13_07_merge_schedule();
extern void test_p13_09_sort_with_many_dup();
extern void test_p13_10_team_picture();
extern void test_p13_11_list_safe_sort();
extern void test_p13_12_salary_cap();
extern void test_p13_08_merge_range();
extern void test_p14_00_bootcamp();
extern void test_p14_01_check_bst();
extern void test_p14_02_next_value();
extern void test_p14_03_k_max_values();
extern void test_p14_04_lca();
extern void test_p14_05_const_tree_inorder_log();
extern void test_p14_06_shortest_path();
extern void test_p14_07_a_b_sqrt();
extern void test_p14_08_lowest_height();
extern void test_p14_10_get_range();
extern void test_p14_09_check_complete_sort();
extern void test_p14_011_customer_credit();
extern void test_p15_00_bootcamp();
extern void test_p15_01_hanoi_tower();
extern void test_p15_02_mnemonics();
extern void test_p15_03_safe_qeen();
extern void test_p15_03_1_safe_qeen_enhance();
extern void test_p15_04_permutation();
extern void test_p15_05_power_set();
extern void test_p15_06_subset_len_k();
extern void test_p15_07_bracket_pair_set();
extern void test_p15_08_palindrom();
extern void test_p15_09_gen_binarytree();
extern void test_p15_10_sudoku();
extern void test_p15_11_gray_code();
extern void test_p16_00_finbonacci();
extern void test_p16_00_max_sum_subarray();
extern void test_p16_01_possible_point_case();
extern void test_p16_02_levenshtein_distance();
extern void test_p16_03_array_path();
extern void test_p16_04_binomial_coefficient();
extern void test_p16_05_pattern_in_2by2_array();
extern void test_p16_06_back_pack();
extern void test_p16_07_bedbathandbeyond();
extern void test_p16_08_number_triangle();
extern void test_p16_09_coin_game();
extern void test_p16_10_n_stair_k_steps();
extern void test_p16_11_pretty_text_lines();
extern void test_p16_12_inc_permutation();
extern void test_p17_01_assign_2_job();
extern void test_p17_02_min_latency();

int main() {

    std::cout << bracketStr(helloWorld) << std::endl;

    // Algorithm summary
    //test_a01_01_subset_all();
    //test_a01_02_subset_k_len();
    //test_a01_03_cont_subarray();
    //test_a01_04_permutation();
 
    // Prolem solving in EPI(Elements of Programming Interview in C++)
    //test_p4_1_parity();
    //test_p4_2_bit_swap();
    //test_p4_3_bit_reverse();
    //test_closed_same_bit_cnt_num();
    //test_add_mul_with_bit_op();
    //test_div_with_bit_op();
    //test_pow_bit_op();
    //test_num_reverse();
    //test_palindrom_num();
    //test_p4_10_random_num_bit_op();
    //test_p4_11_intersect_rec();
    //test_p4_tmp_1_4_align();
    //test_p5_1_dutch_flag_partition();
    //test_p5_2_add_one();
    //test_p5_3_mul_bignum();
    //test_p5_4_array_mv();
    //test_p5_5_rem_dup();
    //test_stock_trading();
    //test_p5_7_stock_trading_twice();
    //test_p5_8_quicksort_repeat_big_small();
    //test_p5_9_generate_prime();
    //test_p5_10_permutation_locating();
    //test_p5_11_permutation_next();
    //test_p5_12_sampling_offline();
    //test_p5_13_sampling_online();
    //test_p5_14_random_permutation();
    //test_p5_15_random_subset();
    //test_p5_16_non_uniform_random();
    //test_p5_17_validate_sudoku_sol();
    //test_p5_18_read_spiral_order();
    //test_p5_19_rotate_right();
    //test_p5_20_pascal_triangle();
    //test_p6_1_itos_stoi();
    //test_p6_2_base_transform();
    //test_p6_3_spreadsheet_colum_num();
    //test_p6_4_replace_rm();
    //test_p6_5_palindrom();
    //test_p6_6_reverse_word();
    //test_p6_7_look_and_say();
    //test_p6_8_roman_to_i();
    //test_p6_9_gen_valid_ip();
    //test_p6_10_snake_string();
    //test_p6_11_string_compress();
    //test_p6_12_rabin_karp_search();
    //test_p7_0_linked_list();
    //test_p7_1_merge_sorted_linkedlist();
    //test_p7_2_reverse_linked_list();
    //test_p7_3_cycle_detect();
    //test_p7_4_overlap_check();
    //test_p7_5_test_overlap_check_cycle();
    //test_p7_6_delete_o_1();
    //test_p7_7_remove_kth_from_last();
    //test_p7_8_remove_duplicated();
    //test_p7_9_right_shift();
    //test_p7_10_even_odd_merge();
    //test_p7_11_is_palindrome();
    //test_p7_12_list_partition();
    //test_p7_13_list_int_add();
    //test_p8_1_max_value();
    //test_p8_2_calc_rpn();
    //test_p8_3_parenthesis();
    //test_p8_4_normalize_path();
    //test_p8_5_building_suset();
    //test_p8_6_tree_level();
    //test_p8_7_circular_queue();
    //test_p8_8_que_with_stack();
    //test_p8_9_que_with_max();
    //test_p9_1_check_balanced();
    //test_p9_2_check_symetric();
    //test_p9_3_lca_no_parent_link();
    //test_p9_4_lca_with_parent_link();
    //test_p9_5_path_bit_sum();
    //test_p9_6_find_same_weigh();
    //test_p9_7_inorder_traverse_loop();
    //test_p9_8_k_th_ele_in_inorder_traverse();
    //test_p9_9_successor_o_1();
    //test_p9_10_traverse_s_1();
    //test_p9_11_const_tree();
    //test_p9_12_const_tree_marker();
    //test_p9_13_leaf_list();
    //test_p9_14_exterior_node();
    //test_p9_15_right_sibling();
    //test_p10_heap_bootcamp();
    //test_p10_1_merge_sorted();
    //test_p10_2_sort_k_inc_dec_array();
    //test_p10_3_sort_almost_sorted();
    //test_p10_4_nearest_start();
    //test_p10_5_realtime_median();
    //test_p10_6_max_k_in_max_heap();
    //test_00_binarysearch_bootcamp();
    //test_p11_1_first_k();
    //test_p11_2_same_value_with_idx();
    //test_p11_3_min_in_circular_array();
    //test_p11_4_max_square_root();
    //test_p11_5_square_root_real();
    //test_p11_6_search_sorted_matrix();
    //test_p11_7_min_max();
    //test_p11_8_kth_big();
    //test_p11_9_missing_ip();
    //test_p11_10_dup_missing_ele();
    //test_p12_00_hashtable_boot();
    //test_p12_01_check_palindrom();
    //test_p12_02_anony_mail_with_magazine();
    //test_p12_03_isbn_cache();
    //test_p12_04_lca_with_hash();
    //test_p12_05_closest_dup_str();
    //test_p12_06_min_sub_vect();
    //test_p12_07_min_sub_vect_ordered();
    //test_p12_08_longest_sub_vec();
    //test_p12_09_longest_cont_num_seq();
    //test_p12_10_find_appended_words();
    //test_p12_11_collatz_conjecture();
    //test_p13_00_sort_bootcamp();
    //test_p13_01_intersection_of_sorted_vec();
    //test_p13_02_merge_sorted();
    //test_p13_03_h_index();
    //test_p13_04_rm_dup_name();
    //test_p13_05_impossible_min_num();
    //test_p13_06_calendar_max_dup_sch();
    //test_p13_07_merge_schedule();
    //test_p13_08_merge_range();
    //test_p13_09_sort_with_many_dup();
    //test_p13_10_team_picture();
    //test_p13_11_list_safe_sort();
    //test_p13_12_salary_cap();
    //test_p14_00_bootcamp();
    //test_p14_01_check_bst();
    //test_p14_02_next_value();
    //test_p14_03_k_max_values();
    //test_p14_04_lca();test_p14_06_shortest_path
    //test_p14_05_const_tree_inorder_log();
    //test_p14_06_shortest_path();
    //test_p14_07_a_b_sqrt();
    //test_p14_08_lowest_height();
    //test_p14_09_check_complete_sort();
    //test_p14_10_get_range();
    //test_p14_011_customer_credit();
    //test_p15_00_bootcamp();
    //test_p15_01_hanoi_tower();
    //test_p15_02_mnemonics();
    //test_p15_03_safe_qeen();
    //test_p15_03_1_safe_qeen_enhance();
    //test_p15_04_permutation();
    //test_p15_05_power_set();
    //test_p15_06_subset_len_k();
    //test_p15_07_bracket_pair_set();
    //test_p15_08_palindrom();
    //test_p15_09_gen_binarytree();
    //test_p15_10_sudoku();
    //test_p15_11_gray_code();
    //test_p16_00_finbonacci();
    //test_p16_00_max_sum_subarray();
    //test_p16_01_possible_point_case();
    //test_p16_02_levenshtein_distance();
    //test_p16_03_array_path();
    //test_p16_04_binomial_coefficient();
    //test_p16_05_pattern_in_2by2_array();
    //test_p16_06_back_pack();
    //test_p16_07_bedbathandbeyond();
    //test_p16_08_number_triangle();
    //test_p16_09_coin_game();
    //test_p16_10_n_stair_k_steps();
    //test_p16_11_pretty_text_lines();
    //test_p16_12_inc_permutation();
    //test_p17_01_assign_2_job();
    test_p17_02_min_latency();
    

    return 0;
}